---
- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: install python3
  apt:
    name: python3
    state: latest
    update_cache: yes
